/* UI microcopy that is not CV content (section titles, labels, aria text).
   CV content itself lives in data/content.json. If content.json ever ships a
   top-level `ui` object per language, its keys override these (see main.js).
   Use *asterisks* to mark the serif-italic accent inside a headline. */

export const UI = {
  en: {
    skip: 'Skip to content',
    home: 'Home',
    langSwitch: 'Language',
    themeToggle: 'Toggle dark mode',
    loadError: 'Content could not be loaded. Please reload the page.',
    footer: 'Built with care in Buenos Aires.',

    heroHello: "Hi, I'm",
    heroScroll: 'Scroll',
    heroPhotoAlt: 'Portrait of Juan Lundahl',

    aboutEyebrow: 'About',
    aboutTitle: 'Who I *am.*',
    idHeader: 'Marketing ID',
    idStatus: 'Active',
    idNumberLabel: 'ID No.',
    idNumber: 'MKT-2016-JL',
    idHint: 'Drag or tap the card',
    languagesLabel: 'Languages',

    skillsEyebrow: 'Skills',
    skillsTitle: 'My marketing *funnel.*',
    skillsIntro: 'Four stages, from first impression to loyal customer. Scroll on and the funnel fills plate by plate with the tools I use at each stage.',
    stageOf: (i, n) => `Stage ${i} of ${n}`,
    toolsCount: (n) => `${n} ${n === 1 ? 'tool' : 'tools'}`,
    levelLegend: 'Level',
    levels: { expert: 'Expert', advanced: 'Advanced', intermediate: 'Intermediate', basic: 'Basic' },
    whatIDo: 'What I do here',
    toolkit: 'Toolkit',
    coreLabel: 'Core platform',
    funnelAria: 'Marketing funnel in four stages',
    stagesAria: 'Funnel stages',
    signAria: 'Current funnel stage',
    goToStage: 'Go to stage',
    loopLabel: 'Loyalty feeds awareness',
    outLabel: 'Loyal customers',

    workEyebrow: 'Work',
    workTitle: "Things I've *built.*",
    workIntro: 'Roles and projects, from the latest to the first. Open any card for the details.',
    workCurrent: 'Current role',
    workDetails: 'Details',
    workHide: 'Hide details',
    workDeliverables: 'Key deliverables',

    modes: { onsite: 'On-site', remote: 'Remote', hybrid: 'Hybrid' },

    rangeEyebrow: 'Range',
    rangeTitle: 'Many industries. *One method.*',
    rangeIntro: 'Every sector has its own language. My approach stays the same: understand the audience, build the right system and keep improving it.',
    rangeIndustries: 'Industries I have worked in',
    rangeWhere: 'Where',
    rangeModes: 'Ways of working',
    rangeCollab: 'How I work',
    recLabel: 'Recommendation',
    recTranslation: 'Traducción',
    recTranslationAria: 'Spanish translation',
    recSeeIt: 'See it on LinkedIn',
    newTab: '(opens in a new tab)',

    certEyebrow: 'Certifications',
    certTitle: 'Always *learning.*',
    certCount: (n) => `${n} certifications`,
    certList: 'Certifications',
    certView: 'View credential',
    educationLabel: 'Education',

    achEyebrow: 'Achievements',
    achTitle: 'Proud *moments.*',
    achHint: 'Scroll or swipe',
    achPrev: 'Previous',
    achNext: 'Next',
    achAward: 'Award',
    achMarketsHome: 'Home base: Argentina',
    homeCountry: 'Argentina',
    achMarketsNA: 'NA = North America',
    achMarketsEMEA: 'EMEA (Europe) = my experience is in Europe',
    achMarketsLATAM: 'LATAM = Latin America, with Argentina as my home base',
    achShowCerts: 'Show certifications',
    achHideCerts: 'Hide certifications',

    contactEyebrow: 'Contact',
    contactTitle: "Let's *talk.*",
    contactIntro: 'Always happy to exchange ideas about AI, marketing automation, CRM and martech in B2B and SaaS.',
    contactEmail: 'Email',
    contactLinkedin: 'LinkedIn',
    contactBase: 'Home base',
    resumeLabel: 'Resume',
    resumeEs: 'Resume (ES)',
    resumeEn: 'Resume (EN)',
    resumeEsFile: 'Spanish version, PDF',
    resumeEnFile: 'English version, PDF'
  },
  es: {
    skip: 'Saltar al contenido',
    home: 'Inicio',
    langSwitch: 'Idioma',
    themeToggle: 'Cambiar modo oscuro',
    loadError: 'No se pudo cargar el contenido. Recargá la página.',
    footer: 'Hecho con dedicación en Buenos Aires.',

    heroHello: 'Hola, soy',
    heroScroll: 'Scroll',
    heroPhotoAlt: 'Retrato de Juan Lundahl',

    aboutEyebrow: 'Sobre mí',
    aboutTitle: 'Quién *soy.*',
    idHeader: 'Marketing ID',
    idStatus: 'Activo',
    idNumberLabel: 'N.º ID',
    idNumber: 'MKT-2016-JL',
    idHint: 'Arrastrá o tocá la credencial',
    languagesLabel: 'Idiomas',

    skillsEyebrow: 'Habilidades',
    skillsTitle: 'Mi *embudo* de marketing.',
    skillsIntro: 'Cuatro etapas, desde la primera impresión hasta el cliente fiel. Con el scroll, el embudo se llena chapa por chapa con las herramientas que uso en cada etapa.',
    stageOf: (i, n) => `Etapa ${i} de ${n}`,
    toolsCount: (n) => `${n} ${n === 1 ? 'herramienta' : 'herramientas'}`,
    levelLegend: 'Nivel',
    levels: { expert: 'Experto', advanced: 'Avanzado', intermediate: 'Intermedio', basic: 'Básico' },
    whatIDo: 'Qué hago acá',
    toolkit: 'Herramientas',
    coreLabel: 'Plataforma clave',
    funnelAria: 'Embudo de marketing en cuatro etapas',
    stagesAria: 'Etapas del embudo',
    signAria: 'Etapa actual del embudo',
    goToStage: 'Ir a la etapa',
    loopLabel: 'La fidelidad alimenta el awareness',
    outLabel: 'Clientes fieles',

    workEyebrow: 'Experiencia',
    workTitle: 'Cosas que *construí.*',
    workIntro: 'Roles y proyectos, del más reciente al primero. Abrí cada tarjeta para ver el detalle.',
    workCurrent: 'Rol actual',
    workDetails: 'Detalles',
    workHide: 'Ocultar detalles',
    workDeliverables: 'Entregables clave',

    modes: { onsite: 'Presencial', remote: 'Remoto', hybrid: 'Híbrido' },

    rangeEyebrow: 'Rango',
    rangeTitle: 'Muchas industrias. *Un método.*',
    rangeIntro: 'Cada sector tiene su propio lenguaje. Mi forma de trabajar no cambia: entender a la audiencia, armar el sistema correcto y seguir mejorándolo.',
    rangeIndustries: 'Industrias en las que trabajé',
    rangeWhere: 'Dónde',
    rangeModes: 'Formas de trabajar',
    rangeCollab: 'Cómo trabajo',
    recLabel: 'Recomendación',
    recTranslation: 'Traducción',
    recTranslationAria: 'Traducción al español',
    recSeeIt: 'Verla en LinkedIn',
    newTab: '(se abre en una pestaña nueva)',

    certEyebrow: 'Certificaciones',
    certTitle: 'Siempre *aprendiendo.*',
    certCount: (n) => `${n} certificaciones`,
    certList: 'Certificaciones',
    certView: 'Ver credencial',
    educationLabel: 'Educación',

    achEyebrow: 'Logros',
    achTitle: 'Momentos de *orgullo.*',
    achHint: 'Deslizá para ver más',
    achPrev: 'Anterior',
    achNext: 'Siguiente',
    achAward: 'Premio',
    achMarketsHome: 'Base: Argentina',
    homeCountry: 'Argentina',
    achMarketsNA: 'NA = Norteamérica',
    achMarketsEMEA: 'EMEA (Europa) = mi experiencia es en Europa',
    achMarketsLATAM: 'LATAM = Latinoamérica, con Argentina como mi base',
    achShowCerts: 'Ver certificaciones',
    achHideCerts: 'Ocultar certificaciones',

    contactEyebrow: 'Contacto',
    contactTitle: 'Hablemos *ya.*',
    contactIntro: 'Siempre con gusto para intercambiar ideas sobre IA, automatización de marketing, CRM y martech en B2B y SaaS.',
    contactEmail: 'Email',
    contactLinkedin: 'LinkedIn',
    contactBase: 'Base',
    resumeLabel: 'CV',
    resumeEs: 'CV (ES)',
    resumeEn: 'CV (EN)',
    resumeEsFile: 'Versión en español, PDF',
    resumeEnFile: 'Versión en inglés, PDF'
  },
  de: {
    skip: 'Zum Inhalt springen',
    home: 'Start',
    langSwitch: 'Sprache',
    themeToggle: 'Dunkelmodus umschalten',
    loadError: 'Der Inhalt konnte nicht geladen werden. Bitte lade die Seite neu.',
    footer: 'Mit Sorgfalt in Buenos Aires gebaut.',
    footerNote: 'Diese Seite ist auch auf Deutsch verfügbar; Übersetzung zur Prüfung durch Muttersprachler.',

    heroHello: 'Hallo, ich bin',
    heroScroll: 'Scrollen',
    heroPhotoAlt: 'Porträt von Juan Lundahl',

    aboutEyebrow: 'Über mich',
    aboutTitle: 'Wer ich *bin.*',
    idHeader: 'Marketing ID',
    idStatus: 'Aktiv',
    idNumberLabel: 'ID-Nr.',
    idNumber: 'MKT-2016-JL',
    idHint: 'Karte ziehen oder antippen',
    languagesLabel: 'Sprachen',

    skillsEyebrow: 'Kompetenzen',
    skillsTitle: 'Mein Marketing-*Funnel.*',
    skillsIntro: 'Vier Phasen, vom ersten Eindruck bis zum treuen Kunden. Beim Scrollen füllt sich der Funnel Schild für Schild mit den Tools, die ich in jeder Phase nutze.',
    stageOf: (i, n) => `Phase ${i} von ${n}`,
    toolsCount: (n) => `${n} ${n === 1 ? 'Tool' : 'Tools'}`,
    levelLegend: 'Niveau',
    levels: { expert: 'Experte', advanced: 'Fortgeschritten', intermediate: 'Mittel', basic: 'Grundkenntnisse' },
    whatIDo: 'Was ich hier mache',
    toolkit: 'Toolkit',
    coreLabel: 'Kernplattform',
    funnelAria: 'Marketing-Funnel in vier Phasen',
    stagesAria: 'Phasen des Funnels',
    signAria: 'Aktuelle Phase des Funnels',
    goToStage: 'Zur Phase springen',
    loopLabel: 'Loyalität stärkt die Awareness',
    outLabel: 'Treue Kunden',

    workEyebrow: 'Erfahrung',
    workTitle: 'Was ich *aufgebaut* habe.',
    workIntro: 'Rollen und Projekte, vom neuesten zum ersten. Öffne eine Karte für die Details.',
    workCurrent: 'Aktuelle Rolle',
    workDetails: 'Details',
    workHide: 'Details ausblenden',
    workDeliverables: 'Wichtige Ergebnisse',

    modes: { onsite: 'Vor Ort', remote: 'Remote', hybrid: 'Hybrid' },

    rangeEyebrow: 'Bandbreite',
    rangeTitle: 'Viele Branchen. *Eine Methode.*',
    rangeIntro: 'Jede Branche hat ihre eigene Sprache. Mein Vorgehen bleibt gleich: die Zielgruppe verstehen, das passende System aufbauen und es laufend verbessern.',
    rangeIndustries: 'Branchen, in denen ich gearbeitet habe',
    rangeWhere: 'Wo',
    rangeModes: 'Arbeitsweisen',
    rangeCollab: 'Wie ich arbeite',
    recLabel: 'Empfehlung',
    recTranslation: 'Übersetzung',
    recTranslationAria: 'Deutsche Übersetzung',
    recSeeIt: 'Auf LinkedIn ansehen',
    newTab: '(öffnet in einem neuen Tab)',

    certEyebrow: 'Zertifikate',
    certTitle: 'Immer *am Lernen.*',
    certCount: (n) => `${n} Zertifikate`,
    certList: 'Zertifikate',
    certView: 'Zertifikat ansehen',
    educationLabel: 'Ausbildung',

    achEyebrow: 'Erfolge',
    achTitle: 'Stolze *Momente.*',
    achHint: 'Scrollen oder wischen',
    achPrev: 'Zurück',
    achNext: 'Weiter',
    achAward: 'Auszeichnung',
    achMarketsHome: 'Heimatbasis: Argentinien',
    homeCountry: 'Argentinien',
    achMarketsNA: 'NA = Nordamerika',
    achMarketsEMEA: 'EMEA (Europa) = meine Erfahrung liegt in Europa',
    achMarketsLATAM: 'LATAM = Lateinamerika, mit Argentinien als Heimatbasis',
    achShowCerts: 'Zertifikate anzeigen',
    achHideCerts: 'Zertifikate ausblenden',

    contactEyebrow: 'Kontakt',
    contactTitle: 'Lass uns *reden.*',
    contactIntro: 'Ich tausche mich jederzeit gern über KI, Marketing-Automatisierung, CRM und Martech in B2B und SaaS aus.',
    contactEmail: 'E-Mail',
    contactLinkedin: 'LinkedIn',
    contactBase: 'Heimatbasis',
    resumeLabel: 'Lebenslauf',
    resumeEs: 'Lebenslauf (ES)',
    resumeEn: 'Lebenslauf (EN)',
    resumeEsFile: 'Spanische Version, PDF',
    resumeEnFile: 'Englische Version, PDF'
  }
};
